name: Deploy Lambda Function

on:
  branches: [master,staging,developer]
jobs:
  build:
    name: deploy lambda function
    runs-on: ubuntu-latest
    enviroment: development
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - run: zip -r publish.zip ./app/*
    - run: aws lambda update-function-code --function-name=express-ExpressTestFunction-u0xsqSaMnTqq --zip-file fileb://publish.zip
    - run: cd app && npm ci